version: '3.9'
# docker-compose up --build --force-recreate --no-deps

networks:
  local:
    name: local

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: src/Presentation/ConvertX.To.API/Dockerfile
      args:
        - Mode=Debug
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_HTTPS_PORT=8001
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - postgres
    networks:
      - local
    volumes:
      - ~/.aspnet/https:/https:ro
      - .conversionStorage:/conversionStorage
    
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=kYsiW8133PNw
    restart: always
    ports:
      - "5432:5432"
    networks:
      - local
    volumes:
      - .postgres/:/var/lib/postgresql/data/
      